// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYFSUyC-QNIsxE8hNERNvZKG5V2R9I1sA',
    appId: '1:961340778052:web:1c5b0f29a9d46b072dbe11',
    messagingSenderId: '961340778052',
    projectId: 'travo-app-1d895',
    authDomain: 'travo-app-1d895.firebaseapp.com',
    storageBucket: 'travo-app-1d895.appspot.com',
    measurementId: 'G-PP41SWMWPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmBIlPDd7IehZZsI_8BciMsLnnnFBN2vk',
    appId: '1:961340778052:android:3ae1466b0673adcc2dbe11',
    messagingSenderId: '961340778052',
    projectId: 'travo-app-1d895',
    storageBucket: 'travo-app-1d895.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy0wd67Pug259dHHhhjZg6bfu_v-zokFw',
    appId: '1:961340778052:ios:d253a7bb10b2ddb02dbe11',
    messagingSenderId: '961340778052',
    projectId: 'travo-app-1d895',
    storageBucket: 'travo-app-1d895.appspot.com',
    iosClientId: '961340778052-den3nsi0d86tv2g611gclnsqum15s132.apps.googleusercontent.com',
    iosBundleId: 'com.example.project02',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy0wd67Pug259dHHhhjZg6bfu_v-zokFw',
    appId: '1:961340778052:ios:23091cb453d931032dbe11',
    messagingSenderId: '961340778052',
    projectId: 'travo-app-1d895',
    storageBucket: 'travo-app-1d895.appspot.com',
    iosClientId: '961340778052-mvmpsv1rr62fvi9j1pfgtu0l0mhr7208.apps.googleusercontent.com',
    iosBundleId: 'com.example.project02.RunnerTests',
  );
}
